language: c
script: ./configure ${CONFIG_OPTS} && make -k W=1 ${MAKE_FLAGS}
dist: trusty
compiler: gcc
sudo: required

matrix:
  include:
    - os: linux
      env:
        - MAKE_FLAGS="CFLAGS+=-Werror "

    - os: linux
      env:
        - MATRIX_EVAL="CC=clang"
        - MAKE_FLAGS="CFLAGS+=-Werror "

    - os: linux
      env:
        - MATRIX_EVAL="CFLAGS=-m32 && LDFLAGS=-m32"
        - MAKE_FLAGS="CFLAGS+=-Werror "

    - os: linux
      addons:
        apt:
          packages:
            - gcc-mingw-w64-x86-64
            - mingw-w64-x86-64-dev
      env:
        - CONFIG_OPTS="--host x86_64-w64-mingw32"
        - MATRIX_EVAL="CC=x86_64-w64-mingw32-gcc"
        - MAKE_FLAGS="CFLAGS+=-Werror "

    - os: linux
      addons:
        apt:
          packages:
            - gcc-mingw-w64-i686
            - mingw-w64-i686-dev
      env:
        - CONFIG_OPTS="--host i686-w64-mingw32"
        - MATRIX_EVAL="CC=i686-w64-mingw32-gcc"
        - MAKE_FLAGS="CFLAGS+=-Werror "

    - os: linux
      install:
        - git clone https://git.kernel.org/pub/scm/devel/sparse/sparse.git --branch v0.5.2
        - pushd sparse && make HAVE_LLVM=no && sudo make install HAVE_LLVM=no && popd
      env:
        - MATRIX_EVAL="CC=cgcc"
        - MAKE_FLAGS="CFLAGS=-Wsparse-error CFLAGS+=-Wno-vla CFLAGS+=-Wno-old-initializer CFLAGS+=-Werror "

before_install:
    - eval "${MATRIX_EVAL}"


notifications:
  email:
    recipients:
      - logang@deltatee.com
