#!/bin/sh
########################################################################
##
## Microsemi Switchtec(tm) PCIe Management Library
## Copyright (c) 2017, Microsemi Corporation
##
## Permission is hereby granted, free of charge, to any person obtaining a
## copy of this software and associated documentation files (the "Software"),
## to deal in the Software without restriction, including without limitation
## the rights to use, copy, modify, merge, publish, distribute, sublicense,
## and/or sell copies of the Software, and to permit persons to whom the
## Software is furnished to do so, subject to the following conditions:
##
## The above copyright notice and this permission notice shall be included
## in all copies or substantial portions of the Software.
##
## THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
## OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
## FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL
## THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR
## OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
## ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
## OTHER DEALINGS IN THE SOFTWARE.
##
########################################################################

#Cross complie on all arches

echo
echo " ------------- Native -------------"
echo

make "$@"

echo
echo " -------------- i686 --------------"
echo


export OBJDIR=build_i686
export CFLAGS=-m32
export LDFLAGS=-m32

make "$@"

unset CFLAGS
unset LDFLAGS

echo
echo " --------- Windows 64bit ---------"
echo

export OBJDIR=build_win64
export CC=x86_64-w64-mingw32-gcc

make "$@"

echo
echo " --------- Windows 32bit ---------"
echo

export OBJDIR=build_win32
export CC=i686-w64-mingw32-gcc

make "$@"
